apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - namespace.yaml
  - app.yaml
  - channel.yaml
  - subscription.yaml
  - managedclustersetbinding.yaml
#  - placement.yaml
  - app.yaml
